# Generated by Django 4.1.7 on 2023-03-10 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flash', '0003_remove_questionanswer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('total_right', models.TextField(max_length=50)),
                ('total_wrong', models.TextField(max_length=50)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flash.chapter')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
