# Generated by Django 4.1.7 on 2023-03-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0005_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='time_start',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
